# -*- coding: utf-8 -*-
"""Sentiment Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166ThoJkBsIGw2IsF6SI6nKMDHh9R0_DY
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data = {
    "review": [
        "This product is amazing",
        "I loved the quality",
        "Very useful and good",
        "Excellent purchase",
        "Worst product ever",
        "I hated it",
        "Very bad quality",
        "Not worth the money"
    ],
    "sentiment": [
        "positive", "positive", "positive", "positive",
        "negative", "negative", "negative", "negative"
    ]
}

df = pd.DataFrame(data)
df

df["sentiment"] = df["sentiment"].map({
    "positive": 1,
    "negative": 0
})

X = df["review"]
y = df["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

vectorizer = TfidfVectorizer()

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model = LogisticRegression()
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

print("Accuracy:", accuracy_score(y_test, y_pred))

review = ["The product is really good"]

review_vec = vectorizer.transform(review)
prediction = model.predict(review_vec)

if prediction[0] == 1:
    print("Positive Review")
else:
    print("Negative Review")

